language: python
python:
- 2.7
- 3.6
install:
- pip install pytest
- pip install wheel
script:
- pytest
before_deploy:
- export PACKAGE_VERSION="$(git describe)"
deploy:
  provider: pypi
  user: arnoldosmium
  password:
    secure: OCGDqh82j0Kq9UYcu3/69Cd7uS1vjB9/rAUHCovRPs/BKBewnh6F53Ro11xF+mO+ZPrdyn9smBkivnkBmV6vgBIOxm0TdttuSDoUziAUWUeB334J8ykARsNovNdn5VYyhx7b+9Euryl4spL92CoSiX0kSL0P05HSNkXq0R0uKs2PdhmpccrQCpFyslD6Iz8gP6AYUHZ7xYVW+lypWyJYvYWKAEl61khP6JIL9Pr5pU6qcHJOUblEHifCnNX2a9cW++isW7HRH/ciddz5MWTotCRsDa5qmMttWaNINPcawJKrGPV0aRVEHEVrMvWHt9pCI1KwpOCtX4fQL7QbTcK+ROm/oNXnzrsIALIxsf93SweIImpyjMPgDWyrV8dteuvBWFgU/DHkXqg24sQdz1LtHSwygV8NGf+HuHzetk7tUL7Z+TZTKOreXpSg8pzN9OgacNlfXt0DJzUh2RKJOYwy1sldPQl4Q025Lh21INasobqXeGuumUvJlP/jTgI9niz/8ONiTrOa2R7rxfoT3ung2p5a8/xpdE+c8CzA2ZyOqM/aruFOsjsgBYDFTmDcVfpfAYxw0ebYKG6Pauq+t485CdHVS10h5odW3KccoqdWwjKLhFHz7jfRjyqrXvYEVT3yh6TiVau7bBP75e/T0QNy+POp726/fMDBDCQCs9aqZ54=
  distributions: bdist_wheel
  on:
    python: 3.6
#    tags: true
