language: python
python:
- 2.7
- 3.6
install:
- pip install pytest
- pip install wheel
script:
- pytest
before_deploy:
- export PACKAGE_VERSION="$(git describe)"
deploy:
  provider: pypi
  user: arnoldosmium
  password:
    secure: ezeFGNy/VOUnwbnaNGxO9qz2rC0CLOBCxRURL9teocQHKjjI2VRl+FuLQT0UOpm5Usq6P5EvUpPaOYb+4DT9aeW7NdJNc7ccJ7c6F4PDeMeKux53sFquQXt5K9OgIFDhpC73H/6cbsqBgGexNTQNJwl8slCu0V2WTB+vqrMTMJtUVL2a3OBeRRFHJjNr5w7iAMGzXMYBtzMnN1XwOU5G335gmQek7srJQ0OUw4lNEe5Ld0PMIlmG8sX9ItZineKGPw3CDZT0HJ27ljbW6g8QARiPNuINQE0p1w3mUddRMQVE/CC0+0bslqr0zRcrKlb6KLYu4wRO/ZnmQRTA2G8aehFDEfBX9B91HplU2Mp+vyRp0RH9YgNxwHdNUUAEP2GQgpVrp3v3aa7jcW2Cr1APY3LRDcNGPgdrAY9Cp8U5p8Poky+q8nyveH2sNd8obwoyQjds5ox9hJ74579hVKUAQENlcMa/EZBdYpBHXTnEC5H1mm8EsEHmi0GWQ1Bssa1ZoLZpS90bDKii5+kMrCKR/mdUcKT9japx1+aqEYYFba7qtclcuzeH+4dlayk46dVk/um/HEVQCIIxHrnjosfgIlmDgOBxXw4Lm1K3f2wjJ6e9SxrN14LsS8R7fDvNkKtmRGfozsGGY2fxUwV6m6Y69l54Bx+JqThNMxQQfDyhgR0=
  distributions: bdist_wheel
  on:
    python: 3.6
