language: python
python:
- 2.7
- 3.6
install:
- pip install pytest
- pip install wheel
script:
- pytest
deploy:
  provider: pypi
  user: arnoldosmium
  password:
    secure: NfbaxdfWTvpc3W1Y3JAtBa9lzETOLWxffvj22W7i/rCjfBes1n4QaL0Q1jxZ9Plk3ci/0MKZoC6FLzzSdUXiqhOjiHL7fSzusA4xBfmWFwQRyk8z0p4opoHaaPctnAykUysvqCxWVzfmLGqFahUh63Eslsra8vuVlhxJKinDa9XpmSORb/OjpNF3docpXZSyZJxGX8Y2MWgJQw3Cb/OlBCXr4apNbS6VwIFvOkPiyxU+08NBcD/BjklqLc1elC+ssz298VGG2b2WQvijhDxZEV6QaabRbuEAzMOzvkfywBAPBUeXVQVRX4hUCGgMTIeGJoS3t0vwF2Lkc6jVZzwiCzcOaLWhUj73D8AReU3T0Y7fJ6XJNQDWv2MODijQH1VVAhUH5PGQE/kPIscUwVSIYvbiSd5ZxPS4nbuWjxChZ3TVsfMjeccsWRnWu5myAEmJsZVPlgblR9myts/A4dDqaV81anxgT20mwpYI8IW3mencS3Xnd76tdOVIyf37RtHj8yoRTmj7UCF1ZFAGB6syPq5Dv8PDGGmkfCSb8HH4hubLY9y3KHyASjjeTgB3tlJpox2WfgJY5kHII6fGyzAouIu7LT6Vg1H5568vxj45F+n0mkkRjI44SDHTwUtfhzDquccH5W8ql96/n9xXU8odOPiyfSzDp2rIyxCTCQSAYcg=
  server: https://test.pypi.org/legacy/
  distributions: bdist_wheel
  on:
    python: 3.6
