language: python
python:
- 2.7
- 3.6
install:
- pip install pytest
- pip install wheel
script:
- pytest
deploy:
  provider: pypi
  user: arnoldosmium
  password:
    secure: B95KNlxTaLpuutTJUiSSwoja17Rw1q5s/4SGFQu4rlV+r8JmEGzThBDGXaDZxxAzqf1oFD0Bk1ThP1KjrfxSBoKOYStrvMZmHNfCWSV0Oo3tVxfdaXInLOcHlEihZHaZu6wOWkJ34xOrwxTB/F4E5r+OP9xvpcb/SDXMJqm/UWdrYlVd4n3Jdl6aJjFHSOIPX+4OUq7fR0OIaxMhZRpi5h4haKqYqjS1g82YMtIHFnh7s6WfuQLqBcEmQUXxuSozTB83sDDIsMF2uVVxZNbJowu3n5R5yH4BTgPr/VAH0wqa4hwH2liVN9we9gEwXqEij//j4UXxTz+pRfj948Pe8dLAG8g0IHHMsl51gusNjpe4FBPX0TBEEBJpWSPlCT/H7cM8JfLH6lGUAUndwSqs+o7292+zLdwgwScKt11N31gwnDZqDwgDmLpQlM+j+znOePjsh9cGTQkV0LsDVcpvVAIo1suICmSvCxhxLsYgkbHhXMhFumWgnn5g1KBPMatycNktR6wcjcPnQnIZiBQDh2ClqVQI6sTIj+f4AvewrI/5HP1S7YLtz8NePr1+b9u3ObCkMYAO4XJW08SWnRoKJs0+YXBqUod7UY+3VgeoWmaJkM7YP9f3NMD3wkgFpQx46QLrp20UpZ0HKJqEG1M7u9RfyEBPR5ER7PkFAR9m/GM=
  server: https://test.pypi.org/legacy/
  distributions: bdist_wheel
  on:
    python: 3.6
